version: 0.1
downloads:
  - name: composer
    downloads:
      - os:
          linux: linux
          macos: macos
        cpu:
          x86_64: x86_64
          arm_64: arm64
        url: https://github.com/matthewbaggett/packaged-tooling/releases/download/${version}/composer-8.2-${os}-${cpu}
tools:
  definitions:
    - name: composer
      download: composer
      known_good_version: 0.0.1
      environment:
        - name: PATH
          list: ["${tool}/bin"]
      shims: [composer]
actions:
  definitions:
    - id: php-automatic-composer-install-on-change
      display_name: "Composer Install when composer.json or composer.lock change"
      triggers:
        - files: [composer.json, composer.lock]
      run: composer install ${target}

    - id: php-automatic-composer-install-on-update
      display_name: "Composer Install when updating from git"
      triggers:
        - git_hooks: [ post-checkout, post-merge ]
      run: composer install ${target}

    - id: php-automatic-composer-update-daily
      display_name: "Composer Update Daily"
      triggers:
        - schedule: 24h
      run: composer update ${target}