version: 0.1
downloads:
  - name: php-cs-fixer
    downloads:
      - os:
          linux: linux
          macos: macos
        cpu:
          x86_64: x86_64
          arm_64: arm64
        url: https://github.com/matthewbaggett/packaged-tooling/releases/download/${version}/php-cs-fixer-8.2-${os}-${cpu}
tools:
  definitions:
    - name: php-cs-fixer
      download: php-cs-fixer
      known_good_version: 0.0.1
      environment:
        - name: PATH
          list: ["${tool}/bin"]
      shims: [php-cs-fixer]
actions:
  definitions:
    - id: php-automatic-php-cs-fixer
      display_name: "Automatically run PHP-CS-Fixer when files change"
      triggers:
        - files: ["**.php"]
      run: php-cs-fixer fix ${target}