version: 0.1
downloads:
  - name: php-cs-fixer
    downloads:
      - os:
          linux: linux
          macos: macos
        cpu:
          x86_64: x86_64
          arm_64: arm64
        url: https://github.com/matthewbaggett/packaged-tooling/releases/download/${version}/php-cs-fixer-8.2-${os}-${cpu}
tools:
  definitions:
    - name: php-cs-fixer
      download: php-cs-fixer
      known_good_version: 0.0.1
      environment:
        - name: PATH
          list: ["${tool}/bin"]
      shims:
        - name: php-cs-fixer
          target: php-cs-fixer
lint:
  definitions:
    - name: php-cs-fixer
      files: [php]
      main_tool: php-cs-fixer
      # tools: [php]
      known_good_version: 0.0.1
      commands:
        - name: lint
          run: php-cs-fixer check --format=json --verbose --using-cache=no --show-progress=none -n ${target}
          output: sarif
          cache_results: true
          success_codes: [0, 4, 8]
          parser:
            runtime: python
            run: python3 ${cwd}/parser.py
        - name: format
          run: php-cs-fixer fix --using-cache=no --show-progress=none -n ${target}
          output: rewrite
          in_place: true
          cache_results: true
          success_codes: [0]
      direct_configs: [.php_cs.dist]
