version: 0.1
downloads:
  - name: cs2pr
    downloads:
      - os:
          linux: linux
          macos: macos
        cpu:
          x86_64: x86_64
          arm_64: arm64
        url: https://github.com/matthewbaggett/packaged-tooling/releases/download/${version}/cs2pr-8.2-${os}-${cpu}
tools:
  definitions:
    - name: cs2pr
      download: cs2pr
      known_good_version: 0.0.1
      environment:
        - name: PATH
          list: ["${tool}/bin"]
      shims:
        - name: cs2pr
          target: cs2pr
