on:
  push:
    branches:
      - main

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.failure_is_acceptable }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - macos-14
        php:
          - 8.2
        phar:
          - php-cs-fixer
        failure_is_acceptable: [false]
        include:
          - phar: php-cs-fixer
            source: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/download/v3.49.0/php-cs-fixer.phar
            extensions: filter,tokenizer,dom,mbstring
    steps:
      - name: Install dependencies
        run: |
          apt-get -qq update 
          apt-get -yqq install git ca-certificates curl wget build-essential

      - name: Clone crazywhalecc/static-php-cli
        uses: actions/checkout@v4
        with:
          repository: crazywhalecc/static-php-cli
          path: static-php-cli

      - name: Setup Runtime
        working-directory: static-php-cli
        run: |
          chmod +x bin/setup-runtime
          bin/setup-runtime
          echo "${{ github.workspace }}/static-php-cli/bin" >> $GITHUB_PATH

      - name: Composer install
        working-directory: static-php-cli
        run: |
          bin/composer install
          chmod +x bin/spc
          bin/spc --version
          echo "${{ github.workspace }}/static-php-cli"
          ls -lh ${{ github.workspace }}/static-php-cli
          echo "${{ github.workspace }}/static-php-cli/bin"
          ls -lh ${{ github.workspace }}/static-php-cli/bin

      - name: Push spc as artifact
        uses: actions/upload-artifact@v2
        with:
          name: spc-${{ runner.os }}-$(uname -m)
          path: ${{ github.workspace }}/static-php-cli/bin/spc

      - name: SPC Doctor
        working-directory: static-php-cli
        run: |
          bin/spc doctor --auto-fix

      - name: SPC Download
        working-directory: static-php-cli
        run: |
          bin/spc download \
            --for-extensions=phar,${{ matrix.extensions }} \
            --with-php=${{ matrix.php }}

      - name: SPC Build
        working-directory: static-php-cli
        run: |
          bin/spc build \
            phar,${{ matrix.extensions }} \
            --build-micro \
            --enable-zts

      - name: Download PHAR (${{ matrix.phar_download }})
        run: |
          mkdir -p ${{ github.workspace }}/phars;
          curl -L -o ${{ github.workspace }}/phars/${{ matrix.phar }}.phar ${{ matrix.source }}

      - name: Build ${{ matrix.phar }}
        working-directory: static-php-cli
        run: |
          mkdir -p ${{ github.workspace }}/out;
          bin/spc \
            micro:combine \
            ${{ github.workspace }}/phars/${{ matrix.phar }}.phar \
            --output ${{ github.workspace }}/out/${{ matrix.phar }}-${{ runner.os }}-$(uname -m)

      - name: Push ${{ matrix.phar }}-${{ runner.os }}-$(uname -m) as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.phar }}-${{ runner.os }}-$(uname -m)
          path: |
            ${{ github.workspace }}/out/*
