name: Build

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yml

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.failure_is_acceptable }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-13
          - macos-14
        php:
          - 8.1
          - 8.2
          - 8.3
        phar:
          - php-cs-fixer
        failure_is_acceptable: [false]
        include:
          - phar: php-cs-fixer
            source: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/download/v3.49.0/php-cs-fixer.phar
            extensions: filter,tokenizer,dom,mbstring
    steps:
      - name: Get Envs
        id: env
        shell: bash
        run: |
          ARCH=$(uname -m)
          echo "Arch: $ARCH"
          SPC_BIN=$(echo "spc-${{ matrix.php }}-${{ runner.os }}-$ARCH" | tr '[:upper:]' '[:lower:]')
          OUTPUT_BIN=$(echo "${{ matrix.phar }}-${{ matrix.php }}-${{ runner.os }}-$ARCH" | tr '[:upper:]' '[:lower:]')
          echo "Output binary: $OUTPUT_BIN"
          CACHE_KEY=$(echo "${{ runner.os }}-$ARCH" | tr '[:upper:]' '[:lower:]')
          {
            echo "arch=$ARCH"
            echo "spc_bin=$SPC_BIN"
            echo "output_bin=$OUTPUT_BIN"
            echo "cache_key=$CACHE_KEY"
          } >> $GITHUB_OUTPUT

      - name: Clone crazywhalecc/static-php-cli
        uses: actions/checkout@v4
        with:
          repository: crazywhalecc/static-php-cli
          path: static-php-cli

      - id: cache
        uses: actions/cache@v4
        with:
          key: ${{ steps.env.outputs.cache_key }}
          path: |
            static-php-cli/vendor
            static-php-cli/downloads

      - name: Setup Runtime
        shell: bash
        working-directory: static-php-cli
        run: |
          chmod +x bin/setup-runtime
          bin/setup-runtime
          echo "${{ github.workspace }}/static-php-cli/bin" >> $GITHUB_PATH

      - name: Composer install
        shell: bash
        working-directory: static-php-cli
        run: |
          bin/composer install
          chmod +x bin/spc
          bin/spc --version
          echo "${{ github.workspace }}/static-php-cli"
          ls -lh ${{ github.workspace }}/static-php-cli
          echo "${{ github.workspace }}/static-php-cli/bin"
          ls -lh ${{ github.workspace }}/static-php-cli/bin

      - name: Push spc as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.env.outputs.spc_bin }}
          path: ${{ github.workspace }}/static-php-cli/bin/spc

      - name: SPC Doctor
        shell: bash
        working-directory: static-php-cli
        run: |
          #if runner.os is 'Linux', run apt update
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            sudo apt-get -qq update
          fi

          bin/spc doctor --auto-fix

      - name: SPC Download
        shell: bash
        working-directory: static-php-cli
        run: |
          bin/spc download \
            --for-extensions=phar,${{ matrix.extensions }} \
            --with-php=${{ matrix.php }}

      - name: SPC Build
        shell: bash
        working-directory: static-php-cli
        run: |
          bin/spc build \
            phar,${{ matrix.extensions }} \
            --build-micro \
            --enable-zts

      - name: Download PHAR (${{ matrix.source }})
        shell: bash
        run: |
          mkdir -p ${{ github.workspace }}/phars;
          echo "Downloading ${{ matrix.phar }}.phar from ${{ matrix.source }}";
          curl -L \
            -o ${{ github.workspace }}/phars/${{ matrix.phar }}.phar \
            ${{ matrix.source }}

      - name: Build ${{ matrix.phar }}.phar
        shell: bash
        working-directory: static-php-cli
        run: |
          mkdir -p ${{ github.workspace }}/out || true;
          bin/spc \
            micro:combine \
            ${{ github.workspace }}/phars/${{ matrix.phar }}.phar \
            --output ${{ github.workspace }}/out/${{ steps.env.outputs.output_bin }}

      - name: Push ${{ steps.env.outputs.output_bin }} as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.env.outputs.output_bin }}
          path: |
            ${{ github.workspace }}/out/${{ steps.env.outputs.output_bin }}
